# 	遇到的问题
##	在开发环境启动时提示
```js
<--- Last few GCs --->

[4499:0x103003000]   155775 ms: Scavenge 1259.2 (1424.4) -> 1258.5 (1424.4) MB, 4.0 / 0.0 ms  (average mu = 0.305, current mu = 0.267) allocation failure 
[4499:0x103003000]   155786 ms: Scavenge 1259.4 (1424.4) -> 1258.8 (1424.4) MB, 4.2 / 0.0 ms  (average mu = 0.305, current mu = 0.267) allocation failure 
[4499:0x103003000]   155797 ms: Scavenge 1259.6 (1424.4) -> 1259.0 (1424.9) MB, 3.6 / 0.0 ms  (average mu = 0.305, current mu = 0.267) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xce72aac9741]
Security context: 0x04013de1d9f1 <JSObject>
    1: stringSlice(aka stringSlice) [0x40180127371] [buffer.js:~582] [pc=0xce72b035052](this=0x0401508025b1 <undefined>,0x04014a4aa969 <Uint8Array map = 0x4012c549ba1>,0x04013de40451 <String[4]: utf8>,0,566)
    2: toString [0x401e6419af1] [buffer.js:~636] [pc=0xce72b02ec71](this=0x04014a4aa969 <Uint8Array map = 0x4012c549ba1>,0x04013de40451 <String[4]: utf8>...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1000623a3 node::Abort() [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
 2: 0x100062c0a node::FatalTryCatch::~FatalTryCatch() [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
 3: 0x1001a2227 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
 4: 0x1001a21c4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
 5: 0x1005a68a2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
 6: 0x1005a8dd3 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
 7: 0x1005a5308 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
 8: 0x1005a34c5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
 9: 0x1005afd6c v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
10: 0x1005afdef v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
11: 0x1005816d5 v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
12: 0x10058197a v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
13: 0x1001c2e88 v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
14: 0x1000d3bd0 node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
15: 0x1000505ec void node::Buffer::(anonymous namespace)::StringSlice<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/mazhaoyuan/.nvm/versions/node/v11.2.0/bin/node]
16: 0xce72aac9741 
17: 0xce72b035052 
```

+	爆了以上的错误
+ 	网上没有资料
+  然后根据自己的时间点,也就是昨天还是好的,今天就有问题,那么问题可能出在这中间写的代码上
+  然后注释掉mock的功能,发现项目可以正常启动
+  然后就定位到了,可能是某个模块的mock数据时出现了问题,然后再去验证
+  查到了mock的具体文件,发现无意中发现了一行import 代码,然后看了提交记录,发现是有同事多加了一行es6导入代码
+  删掉就解决了